### ISSUE TITLE
Some example links in the docs are broken.

### ISSUE THREAD

**Issue by orangeseeds** [go-kratos/go-kratos.dev#182]
At https://go-kratos.dev/en/docs/getting-started/examples, the HTTP section's handler and health links lead to a 404 error on GitHub.

**Comment by etxv** [comment]
health module not found

**Comment by Mo3et** [comment]
I solve this problem in #192. You can read [EN Docs](https://go-kratos.dev/en/docs/getting-started/examples/) when the maintainer merge this PR.
