### ISSUE TITLE
首页左下角的小蓝鸟和 FB 的图标换掉吧。

### ISSUE THREAD

**Issue by kvii** [go-kratos/go-kratos.dev#206]
<img width="356" alt="image" src="https://github.com/go-kratos/go-kratos.dev/assets/56432636/446652e6-80ea-4c74-9c41-a7db76fa2bf0">

首页左下角的小蓝鸟和 FB 的图标对应分别是 blog 和 github 的 kratos discussions，并不是推特和脸书的链接。要不换掉这俩图标吧。

**Comment by mo3et** [comment]
应该是当时贪方便，直接在theme上改了链接而已吧。如果有找到适合的icon，应该可以直接提个PR把他改了。

**Comment by kvii** [comment]
下面这俩怎么样？

* blog 图标用 rss 链接的图标。因为 kratos blog 没有专属的图标。要是用 rss 图标的话，希望也能给个 rss 订阅功能。
<img width="89" alt="image" src="https://github.com/go-kratos/go-kratos.dev/assets/56432636/ee158d22-9959-4764-b35e-955ab70fcb34">

* discussions 图标就用 github discussions 的那个图标。不过这个图标辨识度不是很高，不加文字的话不好辨认。
<img width="124" alt="image" src="https://github.com/go-kratos/go-kratos.dev/assets/56432636/a4024112-5224-423f-bfc5-35422e08a982">

不太清楚是不是还要考虑版权问题。突然感觉好麻烦啊……

**Comment by mo3et** [comment]
那两个也不太对 ;)
因为这个docs生成是用静态页面工具生成的，看代码应该是用的 `docusaurus` 创建的，这些通常使用的话，是基于一些主题来生成的。所以上述我们提到的图标，应该是得在对应的theme里面找，不然图标的割裂感会很强(例如同时用了黑、白两个主题的图标)。  
要修改的话可能是在 [theme/footer](https://github.com/go-kratos/go-kratos.dev/tree/main/src/theme/Footer) 等地方进行修改，不过我对 react 和 docusaurus 不熟悉，可能需要研究一下对应的框架和主题。
