### ISSUE TITLE
development server 运行时切换语言为英文将会导致 404 错误

### ISSUE THREAD

**Issue by ymh199478** [go-kratos/go-kratos.dev#44]
以 development server 在本地运行时，如果切换语言到英文，不能正常预览，提示：

```
Page Not Found
We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.
```

**Comment by Windfarer** [comment]
这个我之前也发现了，好像是docusaurus的bug，build出来的是正常的。

**Comment by ymh199478** [comment]
根据查阅 i18n 资料：https://docusaurus.io/docs/i18n/tutorial 这并不是一个bug

对于非默认语言的其他语言需要使用：`yarn run start -- --locale en` 启动
