### ISSUE TITLE
Documentation difficult to understand due to grammatical errors.

### ISSUE THREAD

**Issue by Jaskerv** [go-kratos/go-kratos.dev#78]
Hey,

Just trying out Kratos, when reading through the documentation, there are several grammatical errors within the English version of the doc.

Such as the "Overview" page, this page describes why Kratos is a tool that a developer should use. However, reading it involves some form of interpretation and may include some confusion especially to those who are learning about microservices with Golang.

I think if you could fix and add more updates to the English documentation, you could get more people to use Kratos.

**Comment by Windfarer** [comment]
Hello, we are preparing a better documents, but it may take some time. If you find any mistake in the docs, you could tell us in [our discord channel](https://discord.gg/BWzJsUJ), so that we can fix it as soon as possible.
